# Generated by Django 5.2.6 on 2026-03-24 16:17

import uuid

import django.db.models.deletion

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.UNDO_REVISION_SCOPE_MODEL),
        ("contenttypes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Revision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.UNDO_REVISION_SCOPE_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("object_id", models.UUIDField()),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "revision",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="undo_revision.revision"),
                ),
            ],
        ),
    ]
